var helper = require('./helper');
var Field = require('./field');
var _ = require('lodash');

var Promise = require('bluebird');

function Model(data) {

    this.$data = data;


}
//<editor-fold desc="isNew || isExists">
Model.prototype.$setExists = function () {
    this.privateTmp().exists = true;
    return this;
}
Model.prototype.isExists = function () {
    return this.privateTmp().exists ? true : false;
}
Model.prototype.isNew = function () {
    return !this.isExists()
}
//</editor-fold>

helper.mixin(Model.prototype, ['container', 'knex', 'schema', 'privateTmp']);


//<editor-fold desc="get set">
Model.prototype.data = function () {
    return this.$data || (this.$data = {});
}
Model.prototype.$dbData = function (dbData) {

    var self = this;
    self.$data = {};
    self.schema().$eachFields(function (field) {
        var mdN = field.name();
        var dbN = field.dbName();
        if (dbN in dbData)
            self.$data[mdN] = dbData[dbN];
    });


    return self;
}
Model.prototype.modifiedData = function () {
    return this.$modifiedData || (this.$modifiedData = {});
}

Model.prototype.hasValue = function (name) {
    var data = this.data();
    var modifiedData = this.modifiedData();

    return name in modifiedData || name in data
}
Model.prototype.pk = function () {
    var pk = this.schema().pk();
    return this.get(pk.name());
}

Model.prototype.$get = function (name) {
    var data = this.data();
    var modifiedData = this.modifiedData();

    return modifiedData[name] || data[name]
}
Model.prototype.get = function (name) {
    var self = this, field = this.schema().field(name);


    if (field.isLazy()) {

        return function (callback) {
            return helper.promise(callback, function () {

                if (self.hasValue(name)) {
                    return Promise.resolve(field.cast(self.$get(name), this));
                }

                if (self.isNew()) {
                    return Promise.resolve(undefined);
                }


                var pk = self.schema().pk();
                var q = self.schema().createQuery();


                pk.where(q, self.get(pk.name()), self);


                return q
                    .setSelect(field.name())
                    .first()
                    .resultRaw()
                    .then(function (result) {
                        console.log(12, result)
                        var val = undefined;
                        if (result) {
                            val = result[field.dbName()];
                        }

                        return (self.data()[field.name()] = val)
                    })
                    .then(function (val) {
                        return field.cast(val, this)
                    })


            })
        }
    }

    return self.hasValue(name) && field.cast(self.$get(name), this);
}

Model.prototype.set = function (name, value) {
    var data = this.data();
    var modifiedData = this.modifiedData();

    if (data[name] != value) {
        modifiedData[name] = value
        this.$modified = true;
    }

    return this
}
Model.prototype.isModified = function (name) {
    var modifiedData = this.modifiedData();
    if (name) return name in modifiedData;
    return this.$modified ? true : false
}
//</editor-fold>


//<editor-fold desc="save">
Model.prototype.save = function (callback) {
    var self = this;
    var method, w8;


    if (self.isExists()) {
        w8 = self.$$waitPostLoad();
        method = self
            .$update()

    } else {
        w8 = self.$$waitPostCreate();
        method = self
            .$insert()
    }

    return helper.promise(callback, function () {
        return w8
            .then(function () {
                return self.schema().emit('preSave', self)
            })
            .then(function () {
                return method;
            })
            .then(function () {
                return self.schema().emit('postSave', self)
            })
            .then(function () {
                return self
            })
    })
}
//</editor-fold>

//<editor-fold desc="insert">
Model.prototype.$insertValue = function () {
    var self = this, data = {}
    this.schema().$eachFields(function (f) {
        if (f.isVirtual())  return;
        var n = f.name();
        if (self.hasValue(n)) {
            data[f.dbName()] = f.dbCast(self.$get(n), self);
            if (data[f.dbName()] === undefined) data[f.dbName()] = f.defaultValue()
        } else {
            var gen = f.autoGenerated();
            if (gen) {
                data[f.dbName()] = self.schema().container().generateValue(gen, self.schema(), f);
            }
        }
    })
    return Promise.props(data)
}
Model.prototype.$insert = function () {
    var self = this;

    return self.$$waitPostCreate()
        .then(function () {
            return self.schema().emit('preInsert', self)
        })
        .then(function () {

            return self
                .$insertValue()
                .then(function (data) {

                    return self.schema().createQuery()
                        .insert(data)
                        .resultRaw(function (dbResult) {
                            self.$dbData(data);
                            self.$setExists();
                        });
                });
        })
        .then(function () {
            return self.schema().emit('postInsert', self);
        })

}
//</editor-fold>
//<editor-fold desc="update">
Model.prototype.$updateValue = function () {
    var self = this, data = {}
    this.schema().$eachFields(function (f) {
        if (f.isVirtual())  return;
        if (self.isModified(f.name())) {
            data[f.dbName()] = f.dbCast(self.$get(f.name(), self))
        }
    })
    return Promise.props(data)
}
Model.prototype.$update = function () {
    var self = this;


    return self.$$waitPostLoad()
        .then(function () {
            return self.schema().emit('preUpdate', self)
        })
        .then(function () {
            if (self.isModified())
                return self
                    .$updateValue()
                    .then(function (data) {
                        var pk = self.schema().pk();
                        var q = self.schema().createQuery()
                            .update(data)


                        pk.where(q, self.get(pk.name()), self);

                        return q.resultRaw(function () {
                            return true;
                        });
                    })
            else return false;
        })
        .then(function () {
            return self.schema().emit('postUpdate', self);
        })
}
//</editor-fold>

//<editor-fold desc="$$waitPostCreate || $$waitPostLoad">
Model.prototype.$$waitPostCreate = function () {
    var self = this;
    return new Promise(function (resolve, reject) {
        function w8(delay) {
            if (self.$$postCreate) return resolve();
            setTimeout(w8, delay || 10);
        }

        w8(20);
    });
}
Model.prototype.$$waitPostLoad = function () {
    var self = this;
    return new Promise(function (resolve, reject) {
        function w8(delay) {
            if (self.$$postLoad) return resolve();
            setTimeout(w8, delay || 10);
        }

        w8(20);
    });
}
//</editor-fold>

Model.prototype.isValid = function (group, callback) {
    var self = this;
    if (_.isFunction(group)) {
        callback = group;
        group = undefined;
    }

    var rules = self.schema().$buildValidator(group);
    var validator = self.schema().container().validator();


    return helper.promise(callback, function () {


        return validator(self, rules, function (path, model) {
            return Promise.resolve(model.get(path));
        })
            .then(function (r) {
                return r
            })


    })
}


module.exports = Model;